version: '3.9'

services:

  database:
    container_name: postgres
    image: postgres:15
    ports:
      - ${DB_OUT_PORT}:5432
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_DB}
      PGDATA: "/var/lib/postgresql/data/pgdata"
    volumes:
      - ./artifacts/db:/var/lib/postgresql/data/pgdata

  das:
    build: .
    container_name: das
    ports:
      - 8080:8080
    environment:
      DB_CONNECTION: ${DB_CONNECTION}