version: '3.9'

services:
  database:
    container_name: postgres
    image: postgres:15
    ports:
      - ${POSTGRES_OUT_PORT}:5432
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
      PGDATA: "/var/lib/postgresql/data/pgdata"
    volumes:
      - ./artifacts/db:/var/lib/postgresql/data/pgdata