version: '3.9'

services:

  database:
    container_name: postgres
    image: postgres:15
    ports:
      - ${POSTGRES_OUT_PORT}:5432
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
      PGDATA: "/var/lib/postgresql/data/pgdata"
    volumes:
      - ${POSTGRES_PGDATA}:/var/lib/postgresql/data/pgdata

  das:
    build: .
    depends_on:
      - database
    container_name: das
    ports:
      - 8080:8080
    environment:
      POSTGRES_HOST: database