version: '3.9'

services:
  database:
    container_name: postgres
    image: postgres:15
    ports:
      - 5431:5432
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: admin
      POSTGRES_DB: ${POSTGRES_DB}
      PGDATA: "/var/lib/postgresql/data/pgdata"
    volumes:
      - ./artifacts/db:/var/lib/postgresql/data/pgdata