version: '3.9'

services:

  database:
    container_name: mysql
    image: mysql:5.7.22
    ports:
      - ${DB_OUT_PORT}:3306
    environment:
      MYSQL_ROOT_PASSWORD: ${DB_ROOT_PASSWORD}
      MYSQL_USER: ${DB_USER}
      MYSQL_PASSWORD: ${DB_PASSWORD}
      MYSQL_DATABASE: ${DB_NAME}
      #DB_DATA: "/var/lib/mysql"
    volumes:
      - ${DB_DATA}:/var/lib/msql

  das:
    image: alekseikovtun/das:latest
    depends_on:
      - database
    container_name: das
    ports:
      - 8080:8080
    environment:
      DB_HOST: database
      DB_USER: ${DB_USER}
      DB_PASSWORD: ${DB_PASSWORD}
      DB_NAME: ${DB_NAME}
      DB_OUT_PORT: ${DB_OUT_PORT}
      MYSQL_ROOT_PASSWORD: ${DB_ROOT_PASSWORD}
      MYSQL_USER: ${DB_USER}
      MYSQL_PASSWORD: ${DB_PASSWORD}
      MYSQL_DATABASE: ${DB_NAME}
