version: '3.9'

services:

  database:
    container_name: mysql
    image: mysql:5.7.22
    ports:
      - ${DB_OUT_PORT}:3306
    environment:
      MYSQL_ROOT_PASSWORD: ${DB_ROOT_PASSWORD}
      MYSQL_USER: ${DB_USER}
      MYSQL_PASSWORD: ${DB_PASSWORD}
      MYSQL_DATABASE: ${DB_NAME}
      #DB_DATA: "/var/lib/mysql"
    volumes:
      - ${DB_DATA}:/var/lib/msql
    healthcheck:
      test: mysqladmin ping -h localhost -u $$MYSQL_USER --password=$$MYSQL_PASSWORD
      interval: 5s
      timeout: 5s
      retries: 20

  das:
    image: alekseikovtun/das:latest
    depends_on:
      database:
        condition: service_healthy
    container_name: das
    ports:
      - 8080:8080
    environment:
      DB_HOST: database
      DB_USER: ${DB_USER}
      DB_PASSWORD: ${DB_PASSWORD}
      DB_NAME: ${DB_NAME}
      DB_OUT_PORT: ${DB_OUT_PORT}
      MYSQL_ROOT_PASSWORD: ${DB_ROOT_PASSWORD}
      MYSQL_USER: ${DB_USER}
      MYSQL_PASSWORD: ${DB_PASSWORD}
      MYSQL_DATABASE: ${DB_NAME}
      MYSQL_HOST: database
    restart: on-failure

  adminer:
    image: adminer
    restart: always
    ports:
      - 8888:8080