"""new migrations

Revision ID: 015ae30b2f72
Revises: 8f51a017bf9c
Create Date: 2023-04-07 08:23:51.287489

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '015ae30b2f72'
down_revision = '8f51a017bf9c'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('alert', 'name',
               existing_type=mysql.VARCHAR(length=255),
               type_=mysql.VARCHAR(length=255),
               existing_nullable=False)
    op.alter_column('alert', 'solution',
               existing_type=mysql.VARCHAR(length=255),
               type_=sa.TEXT(),
               existing_nullable=True)
    op.alter_column('all_logs', 'context',
               existing_type=mysql.VARCHAR(length=255),
               type_=sa.TEXT(),
               existing_nullable=True)
    op.alter_column('drone_log', 'log_content',
               existing_type=mysql.VARCHAR(length=255),
               type_=sa.TEXT(),
               existing_nullable=True)
    op.alter_column('log', 'log_content',
               existing_type=mysql.VARCHAR(length=1024),
               type_=sa.TEXT(),
               existing_nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('log', 'log_content',
               existing_type=sa.TEXT(length=16777215),
               type_=mysql.VARCHAR(length=1024),
               existing_nullable=True)
    op.alter_column('drone_log', 'log_content',
               existing_type=sa.TEXT(length=16777215),
               type_=mysql.VARCHAR(length=64),
               existing_nullable=True)
    op.alter_column('all_logs', 'context',
               existing_type=sa.TEXT(length=16777215),
               type_=mysql.VARCHAR(length=255),
               existing_nullable=True)
    op.alter_column('alert', 'solution',
               existing_type=sa.TEXT(length=16777215),
               type_=mysql.VARCHAR(length=64),
               existing_nullable=True)
    op.alter_column('alert', 'name',
               existing_type=sa.TEXT(length=16777215),
               type_=mysql.VARCHAR(length=64),
               existing_nullable=False)
    # ### end Alembic commands ###
