"""new migrations

Revision ID: 123a71e11825
Revises: 7a407139a384
Create Date: 2023-05-13 17:01:02.080830

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '123a71e11825'
down_revision = '7a407139a384'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('task', 'priority')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('task', sa.Column('priority', mysql.VARCHAR(length=64), nullable=True))
    # ### end Alembic commands ###
