"""Add priority

Revision ID: 29df5476034c
Revises: 4db5c493393e
Create Date: 2022-11-06 14:25:41.073782

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '29df5476034c'
down_revision = '4db5c493393e'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('task_status', sa.Column('priority', sa.String(length=20), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('task_status', 'priority')
    # ### end Alembic commands ###
