"""new migrations

Revision ID: 2accaab43d7f
Revises: e76e8ae493e8
Create Date: 2023-02-22 18:56:15.038947

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2accaab43d7f'
down_revision = 'e76e8ae493e8'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
