"""new migrations

Revision ID: 5529299ca18f
Revises: 4fbba37a2562
Create Date: 2023-03-03 09:49:19.632595

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '5529299ca18f'
down_revision = '4fbba37a2562'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('log', 'log_content',
               existing_type=mysql.VARCHAR(length=64),
               type_=sa.VARCHAR(length=1024),
               existing_nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('log', 'log_content',
               existing_type=sa.VARCHAR(length=1024),
               type_=mysql.VARCHAR(length=64),
               existing_nullable=True)
    # ### end Alembic commands ###
