"""new migrations

Revision ID: 597b4393d872
Revises: 
Create Date: 2023-03-06 17:48:26.782113

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '597b4393d872'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('cargo',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('weight', sa.Float(), nullable=True),
    sa.Column('volume', sa.Float(), nullable=True),
    sa.Column('name', sa.VARCHAR(length=64), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('drone_type',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('engine_power', sa.Float(), nullable=True),
    sa.Column('flight_range', sa.Float(), nullable=True),
    sa.Column('load_capacity', sa.Float(), nullable=True),
    sa.Column('cargo_volume', sa.Float(), nullable=True),
    sa.Column('battery_capacity', sa.Float(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('log',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.TIMESTAMP(timezone=True), nullable=True),
    sa.Column('log_content', sa.VARCHAR(length=1024), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('drone',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('access_key', sa.VARCHAR(length=64), nullable=True),
    sa.Column('drone_status', sa.VARCHAR(length=64), nullable=False),
    sa.Column('place_number', sa.Integer(), nullable=True),
    sa.Column('id_drone_type', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['id_drone_type'], ['drone_type.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('task',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.TIMESTAMP(timezone=True), nullable=True),
    sa.Column('updated_at', sa.TIMESTAMP(timezone=True), nullable=True),
    sa.Column('gps_latitude', sa.Float(), nullable=True),
    sa.Column('gps_longitude', sa.Float(), nullable=True),
    sa.Column('priority', sa.VARCHAR(length=64), nullable=True),
    sa.Column('task_status', sa.VARCHAR(length=64), nullable=False),
    sa.Column('completed_at', sa.TIMESTAMP(timezone=True), nullable=True),
    sa.Column('id_drone', sa.Integer(), nullable=True),
    sa.Column('id_cargo', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['id_cargo'], ['cargo.id'], ),
    sa.ForeignKeyConstraint(['id_drone'], ['drone.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('drone_log',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('log_content', sa.VARCHAR(length=64), nullable=True),
    sa.Column('id_task', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['id_task'], ['task.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('flight',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('started_at', sa.TIMESTAMP(timezone=True), nullable=True),
    sa.Column('finished_at', sa.TIMESTAMP(timezone=True), nullable=True),
    sa.Column('estimated_at', sa.TIMESTAMP(timezone=True), nullable=True),
    sa.Column('deviation', sa.Float(), nullable=True),
    sa.Column('id_task', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['id_task'], ['task.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('alert',
    sa.Column('name', sa.VARCHAR(length=64), nullable=False),
    sa.Column('solution', sa.VARCHAR(length=64), nullable=True),
    sa.Column('log', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['log'], ['drone_log.id'], ),
    sa.PrimaryKeyConstraint('name')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('alert')
    op.drop_table('flight')
    op.drop_table('drone_log')
    op.drop_table('task')
    op.drop_table('drone')
    op.drop_table('log')
    op.drop_table('drone_type')
    op.drop_table('cargo')
    # ### end Alembic commands ###
