"""new migrations

Revision ID: 6973aed6ed90
Revises: e7c40c50ccb5
Create Date: 2023-03-29 13:43:58.933223

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '6973aed6ed90'
down_revision = 'e7c40c50ccb5'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
