"""new migrations

Revision ID: 726107eeda0b
Revises: 015ae30b2f72
Create Date: 2023-04-14 10:55:22.142710

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '726107eeda0b'
down_revision = '015ae30b2f72'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('drone_login_data',
    sa.Column('drone_id', sa.Integer(), nullable=False),
    sa.Column('login', sa.TEXT(), nullable=True),
    sa.Column('password', sa.TEXT(), nullable=True),
    sa.Column('refresh_token', sa.TEXT(), nullable=True),
    sa.Column('active_token', sa.TEXT(), nullable=True),
    sa.PrimaryKeyConstraint('drone_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('drone_login_data')
    # ### end Alembic commands ###
