"""new migrations

Revision ID: 8f51a017bf9c
Revises: 803da31306e4
Create Date: 2023-04-05 14:45:42.795374

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '8f51a017bf9c'
down_revision = '803da31306e4'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('all_logs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.TIMESTAMP(timezone=True), nullable=True),
    sa.Column('log_type', sa.VARCHAR(length=255), nullable=True),
    sa.Column('context', sa.VARCHAR(length=255), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('all_logs')
    # ### end Alembic commands ###
