"""new migrations

Revision ID: ac74229a7e53
Revises: 5529299ca18f
Create Date: 2023-03-03 12:25:03.830788

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'ac74229a7e53'
down_revision = '5529299ca18f'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('flight', sa.Column('id_task', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'flight', 'task', ['id_task'], ['id'])
    op.drop_constraint('task_ibfk_3', 'task', type_='foreignkey')
    op.drop_column('task', 'id_flight')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('task', sa.Column('id_flight', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True))
    op.create_foreign_key('task_ibfk_3', 'task', 'flight', ['id_flight'], ['id'])
    op.drop_constraint(None, 'flight', type_='foreignkey')
    op.drop_column('flight', 'id_task')
    # ### end Alembic commands ###
