"""new migrations

Revision ID: b011a11e00ec
Revises: bae8f6f7e1d5
Create Date: 2023-02-20 20:39:58.923637

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b011a11e00ec'
down_revision = 'bae8f6f7e1d5'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
