"""new migrations

Revision ID: bae8f6f7e1d5
Revises: f11c51001f63
Create Date: 2023-02-20 20:28:26.468094

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'bae8f6f7e1d5'
down_revision = 'f11c51001f63'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
