"""new migrations

Revision ID: cd62f8db5d2f
Revises: 6973aed6ed90
Create Date: 2023-03-31 08:44:10.416785

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'cd62f8db5d2f'
down_revision = '6973aed6ed90'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('flight', 'estimated_at')
    op.drop_column('flight', 'deviation')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('flight', sa.Column('deviation', mysql.FLOAT(), nullable=True))
    op.add_column('flight', sa.Column('estimated_at', mysql.TIMESTAMP(), nullable=True))
    # ### end Alembic commands ###
