"""new migrations

Revision ID: e76e8ae493e8
Revises: b011a11e00ec
Create Date: 2023-02-20 20:42:19.923532

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e76e8ae493e8'
down_revision = 'b011a11e00ec'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
