"""new migrations

Revision ID: e7c40c50ccb5
Revises: eb0367a98ecf
Create Date: 2023-03-24 08:27:53.000797

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'e7c40c50ccb5'
down_revision = 'eb0367a98ecf'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
