"""new migrations

Revision ID: eb0367a98ecf
Revises: 597b4393d872
Create Date: 2023-03-15 17:17:09.665094

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'eb0367a98ecf'
down_revision = '597b4393d872'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('charging_point',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('power', sa.Float(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('charging_point_to_drone',
    sa.Column('charging_point_id', sa.Integer(), nullable=True),
    sa.Column('drone_id', sa.Integer(), nullable=True),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['charging_point_id'], ['charging_point.id'], ),
    sa.ForeignKeyConstraint(['drone_id'], ['drone.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('charging_point_to_drone')
    op.drop_table('charging_point')
    # ### end Alembic commands ###
