"""new migrations

Revision ID: f1d140ff0497
Revises: 726107eeda0b
Create Date: 2023-05-04 01:22:56.673044

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'f1d140ff0497'
down_revision = '726107eeda0b'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('drone_login_data')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('drone_login_data',
    sa.Column('drone_id', mysql.INTEGER(display_width=11), autoincrement=True, nullable=False),
    sa.Column('login', mysql.TEXT(), nullable=True),
    sa.Column('password', mysql.TEXT(), nullable=True),
    sa.Column('refresh_token', mysql.TEXT(), nullable=True),
    sa.Column('active_token', mysql.TEXT(), nullable=True),
    sa.PrimaryKeyConstraint('drone_id'),
    mysql_default_charset='latin1',
    mysql_engine='InnoDB'
    )
    # ### end Alembic commands ###
