"""empty message

Revision ID: f64dee634bc8
Revises: f2180d7f80db
Create Date: 2022-11-08 19:39:57.894107

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f64dee634bc8'
down_revision = 'f2180d7f80db'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('drone_status', 'departure_latitude')
    op.drop_column('drone_status', 'departure_longitude')
    op.add_column('drone_status', sa.Column('departure_latitude', sa.Float(), nullable=True))
    op.add_column('drone_status', sa.Column('departure_longitude', sa.Float(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('drone_status', 'departure_latitude')
    op.drop_column('drone_status', 'departure_longitude')
    op.add_column('drone_status', sa.Column('departure_latitude', sa.Integer(), nullable=True))
    op.add_column('drone_status', sa.Column('departure_longitude', sa.Integer(), nullable=True))
    # ### end Alembic commands ###
